"""Generate blobs.rs from the extracted Microchip UPDI script JSON.

The input JSON is not part of this repository. It is extracted from Microchip's
MPLAB tool pack, and it holds one entry per script name with the bytecode as
hex and the `ri4command` value.

Usage, from the repository root:

    python3 probe-rs/src/probe/pickit/gen_scripts.py \\
        <dx.json> <tiny0.json> > probe-rs/src/probe/pickit/blobs.rs
    cargo fmt

The output needs `cargo fmt` afterwards. This script does not lay out the byte
arrays the way rustfmt does.
"""

import json
import re
import sys

# Pack names use acronyms that Rust spells differently.
ACRONYMS = [
    ("DeviceID", "DeviceId"),
    ("HWBP", "HwBp"),
    ("SIB", "Sib"),
    ("CSreg", "CsReg"),
    ("EEmem", "EeMem"),
    ("IDmem", "IdMem"),
    ("PC", "Pc"),
]


def variant(name):
    """Pack script name to the matching `ScriptName` variant."""
    name = name.removesuffix("_UPDI")
    for old, new in ACRONYMS:
        name = name.replace(old, new)
    return name


def konst(name):
    """Variant name to the name of the static holding its script."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def command(value):
    """`ri4command` string to a Rust literal."""
    value = int(value, 16)
    return f"0x{value >> 16:04x}_{value & 0xffff:04x}"


def blob(hex_bytes):
    return "&[" + ", ".join(f"0x{b:02x}" for b in bytes.fromhex(hex_bytes)) + "]"


def main():
    dx_path, tiny_path = sys.argv[1], sys.argv[2]
    dx = json.load(open(dx_path))
    tiny = json.load(open(tiny_path))

    assert sorted(dx) == sorted(tiny), "the two families have different script sets"
    names = sorted(dx)
    for name in names:
        assert dx[name]["ri4command"] == tiny[name]["ri4command"], name

    w = sys.stdout.write
    w("//! Microchip UPDI script bytecode for the families this driver supports.\n")
    w("//!\n")
    w("//! The bytecode is extracted from Microchip's MPLAB tool pack. It is vendor\n")
    w("//! data and the probe-rs licence does not cover it.\n")
    w("//!\n")
    w("//! Generated by `gen_scripts.py`, not written by hand.\n")
    w("//!\n")
    w("//! Most scripts are byte-identical in both families, so those are stored\n")
    w("//! once. A `DX_` or `TINY0_` prefix marks the ones that are not.\n\n")
    w("use super::scripts::{Script, ScriptName};\n\n")

    for name in names:
        cmd = command(dx[name]["ri4command"])
        if dx[name]["bytes"] == tiny[name]["bytes"]:
            w(f"static {konst(variant(name))}: Script =\n")
            w(f"    Script::from_static({cmd}, {blob(dx[name]['bytes'])});\n")
        else:
            for prefix, table in (("DX_", dx), ("TINY0_", tiny)):
                w(f"static {prefix}{konst(variant(name))}: Script =\n")
                w(f"    Script::from_static({cmd}, {blob(table[name]['bytes'])});\n")
    w("\n")

    for prefix, label, fn in (
        ("DX_", "AVR Dx", "dx"),
        ("TINY0_", "tiny 0-series and 1-series", "tiny0"),
    ):
        w(f"/// The script for `name` on {label} parts.\n")
        w(f"pub(super) fn {fn}(name: ScriptName) -> &'static Script {{\n")
        w("    match name {\n")
        for name in names:
            shared = dx[name]["bytes"] == tiny[name]["bytes"]
            target = konst(variant(name)) if shared else prefix + konst(variant(name))
            w(f"        ScriptName::{variant(name)} => &{target},\n")
        w("    }\n}\n\n")


main()
